/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html, js, ts, vue}", 
    "./src/**/*"
  ],
  theme: {
    screens:{
      xl: '1920px',
      lg: '1440px',
    },
    extend: {
      colors: {
        /* -----link color----- */
        'link-blue': 'rgb(var(--link-blue)/<alpha-value>)',

        /* -----淺色系色票----- */
        'primary-50': 'rgb(var(--primary-50)/<alpha-value>)',
        'primary-100': 'rgb(var(--primary-100)/<alpha-value>)',
        'primary-200': 'rgb(var(--primary-200)/<alpha-value>)',
        'primary-300': 'rgb(var(--primary-300)/<alpha-value>)',
        'primary-400': 'rgb(var(--primary-400)/<alpha-value>)',
        'primary-500': 'rgb(var(--primary-500)/<alpha-value>)',
        'primary-600': 'rgb(var(--primary-600)/<alpha-value>)',
        'primary-700': 'rgb(var(--primary-700)/<alpha-value>)',
        'primary-800': 'rgb(var(--primary-800)/<alpha-value>)',
        'primary-900': 'rgb(var(--primary-900)/<alpha-value>)',

        'secondary-50': 'rgb(var(--secondary-50)/<alpha-value>)',
        'secondary-100': 'rgb(var(--secondary-100)/<alpha-value>)',
        'secondary-200': 'rgb(var(--secondary-200)/<alpha-value>)',
        'secondary-300': 'rgb(var(--secondary-300)/<alpha-value>)',
        'secondary-400': 'rgb(var(--secondary-400)/<alpha-value>)',
        'secondary-500': 'rgb(var(--secondary-500)/<alpha-value>)',
        'secondary-600': 'rgb(var(--secondary-600)/<alpha-value>)',
        'secondary-700': 'rgb(var(--secondary-700)/<alpha-value>)',
        'secondary-800': 'rgb(var(--secondary-800)/<alpha-value>)',
        'secondary-900': 'rgb(var(--secondary-900)/<alpha-value>)',
        'secondary-font': 'rgb(var(--secondary-font)/<alpha-value>)',

        'surface-0': 'rgb(var(--surface-0)/<alpha-value>)',
        'surface-50': 'rgb(var(--surface-50)/<alpha-value>)',
        'surface-100': 'rgb(var(--surface-100)/<alpha-value>)',
        'surface-200': 'rgb(var(--surface-200)/<alpha-value>)',
        'surface-300': 'rgb(var(--surface-300)/<alpha-value>)',
        'surface-400': 'rgb(var(--surface-400)/<alpha-value>)',
        'surface-500': 'rgb(var(--surface-500)/<alpha-value>)',
        'surface-600': 'rgb(var(--surface-600)/<alpha-value>)',
        'surface-700': 'rgb(var(--surface-700)/<alpha-value>)',
        'surface-800': 'rgb(var(--surface-800)/<alpha-value>)',
        'surface-900': 'rgb(var(--surface-900)/<alpha-value>)',

        /* -----功能色色票----- */
        'danger-100': 'rgb(var(--danger-100)/<alpha-value>)',
        'danger-300': 'rgb(var(--danger-300)/<alpha-value>)',
        'danger-400': 'rgb(var(--danger-400)/<alpha-value>)',
        'danger-500': 'rgb(var(--danger-500)/<alpha-value>)',
        'danger-600': 'rgb(var(--danger-600)/<alpha-value>)',

        'yellow-50': 'rgb(var(--yellow-50)/<alpha-value>)',
        'yellow-100': 'rgb(var(--yellow-100)/<alpha-value>)',
        'yellow-200': 'rgb(var(--yellow-200)/<alpha-value>)',
        'yellow-300': 'rgb(var(--yellow-300)/<alpha-value>)',
        'yellow-400': 'rgb(var(--yellow-400)/<alpha-value>)',
        'yellow-500': 'rgb(var(--yellow-500)/<alpha-value>)',
        'yellow-600': 'rgb(var(--yellow-600)/<alpha-value>)',
        'yellow-700': 'rgb(var(--yellow-700)/<alpha-value>)',
        'yellow-800': 'rgb(var(--yellow-800)/<alpha-value>)',
        'yellow-900': 'rgb(var(--yellow-900)/<alpha-value>)',

        'table-blue-100': 'rgb(var(--table-blue-100)/<alpha-value>)',
        'table-blue-200': 'rgb(var(--table-blue-200)/<alpha-value>)',
        'table-blue-500': 'rgb(var(--table-blue-500)/<alpha-value>)',
        'table-blue-800': 'rgb(var(--table-blue-800)/<alpha-value>)',
        'table-blue-900': 'rgb(var(--table-blue-900)/<alpha-value>)',
        'table-orange-100': 'rgb(var(--table-orange-100)/<alpha-value>)',
        'table-orange-200': 'rgb(var(--table-orange-200)/<alpha-value>)',
        'table-orange-300': 'rgb(var(--table-orange-300)/<alpha-value>)',
        'table-orange-500': 'rgb(var(--table-orange-500)/<alpha-value>)',
        'table-orange-800': 'rgb(var(--table-orange-800)/<alpha-value>)',
        'table-orange-900': 'rgb(var(--table-orange-900)/<alpha-value>)',
        'table-green-200': 'rgb(var(--table-green-200)/<alpha-value>)',
        'table-green-500': 'rgb(var(--table-green-500)/<alpha-value>)',
        'table-green-800': 'rgb(var(--table-green-800)/<alpha-value>)',
        'table-green-900': 'rgb(var(--table-green-900)/<alpha-value>)',

        /* -----圖表色票----- */
        'chart-1': 'rgb(var(--chart-1)/<alpha-value>)',
        'chart-2': 'rgb(var(--chart-2)/<alpha-value>)',
        'chart-3': 'rgb(var(--chart-3)/<alpha-value>)',
        'chart-4': 'rgb(var(--chart-4)/<alpha-value>)',
        'chart-5': 'rgb(var(--chart-5)/<alpha-value>)',
        'chart-6': 'rgb(var(--chart-6)/<alpha-value>)',
        'chart-7': 'rgb(var(--chart-7)/<alpha-value>)',
        'chart-8': 'rgb(var(--chart-8)/<alpha-value>)',
        'chart-9': 'rgb(var(--chart-9)/<alpha-value>)',

        /* -----選擇顏色用色票----- */
        'palette-blue': 'rgb(var(--palette-blue)/<alpha-value>)',
        'palette-green': 'rgb(var(--palette-green)/<alpha-value>)',
        'palette-pink': 'rgb(var(--palette-pink)/<alpha-value>)',
        'palette-orange': 'rgb(var(--palette-orange)/<alpha-value>)',
        'palette-sky': 'rgb(var(--palette-sky)/<alpha-value>)',
        'palette-brown': 'rgb(var(--palette-brown)/<alpha-value>)',
        'palette-purple': 'rgb(var(--palette-purple)/<alpha-value>)',

        'palette-blue-secondary': 'rgb(var(--palette-blue-secondary)/<alpha-value>)',
        'palette-green-secondary': 'rgb(var(--palette-green-secondary)/<alpha-value>)',
        'palette-pink-secondary': 'rgb(var(--palette-pink-secondary)/<alpha-value>)',
        'palette-orange-secondary': 'rgb(var(--palette-orange-secondary)/<alpha-value>)',
        'palette-sky-secondary': 'rgb(var(--palette-sky-secondary)/<alpha-value>)',
        'palette-brown-secondary': 'rgb(var(--palette-brown-secondary)/<alpha-value>)',
        'palette-purple-secondary': 'rgb(var(--palette-purple-secondary)/<alpha-value>)',

        /* -----深色系色票----- */
        'primary-dark': 'rgb(var(--primary-dark)/<alpha-value>)',
        'primary-dark-50': 'rgb(var(--primary-dark-50)/<alpha-value>)',
        'primary-dark-100': 'rgb(var(--primary-dark-100)/<alpha-value>)',
        'primary-dark-200': 'rgb(var(--primary-dark-200)/<alpha-value>)',
        'primary-dark-300': 'rgb(var(--primary-dark-300)/<alpha-value>)',
        'primary-dark-400': 'rgb(var(--primary-dark-400)/<alpha-value>)',
        'primary-dark-500': 'rgb(var(--primary-dark-500)/<alpha-value>)',
        'primary-dark-600': 'rgb(var(--primary-dark-600)/<alpha-value>)',
        'primary-dark-700': 'rgb(var(--primary-dark-700)/<alpha-value>)',
      },
      spacing: {
        13: '3.25rem',
        19: '4.75rem',
        21: '5.25rem',
        75: '18.75rem',
        84: '21rem',
        100: '25rem',
        136: '34rem',
        160: '40rem',
      },
    },
  },
  // plugins: [require('tailwindcss-primeui')],
  plugins: [],
  darkMode: true,
}

